# Generated by Django 3.2.7 on 2021-09-28 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_freeversion', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('effect_text', models.CharField(blank=True, max_length=254, null=True)),
                ('allowed_in_phase', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('ALL', 'I-V'), ('NONE', '')], max_length=4)),
                ('attack_all', models.BooleanField(default=False)),
                ('skill_style', models.CharField(choices=[('LN', 'Lightning'), ('FR', 'Fire'), ('GL', 'Golem'), ('DR', 'Drain'), ('IC', 'Ice')], max_length=2)),
                ('mana_cost', models.IntegerField(default=2)),
                ('cards_discard_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.card')),
            ],
        ),
        migrations.CreateModel(
            name='Player_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(choices=[('LN', 'Lightning'), ('FR', 'Fire'), ('IC', 'Ice')], max_length=2)),
                ('image_idle', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_idle_url', models.URLField(blank=True, null=True)),
                ('image_attack', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_attack_url', models.URLField(blank=True, null=True)),
                ('image_die', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_die_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('fire_defense', models.IntegerField(default=0)),
                ('ice_defense', models.IntegerField(default=0)),
                ('drain_defense', models.IntegerField(default=0)),
                ('lightning_defense', models.IntegerField(default=0)),
                ('physical_defense', models.IntegerField(default=0)),
                ('fire_attack_power', models.IntegerField(default=0)),
                ('fire_attack_cost', models.IntegerField(default=4)),
                ('ice_attack_power', models.IntegerField(default=0)),
                ('ice_attack_cost', models.IntegerField(default=2)),
                ('drain_attack_power', models.IntegerField(default=0)),
                ('drain_attack_cost', models.IntegerField(default=1)),
                ('lightning_attack_power', models.IntegerField(default=0)),
                ('lightning_attack_cost', models.IntegerField(default=2)),
                ('golem_attack_power', models.IntegerField(default=0)),
                ('golem_attack_cost', models.IntegerField(default=2)),
                ('healing_power', models.IntegerField(default=0)),
                ('healing_attack_cost', models.IntegerField(default=0)),
                ('mana_current', models.IntegerField(default=0)),
                ('mana_max', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('health_current', models.IntegerField(default=0)),
                ('health_max', models.IntegerField(default=0)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.player_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
