# Generated by Django 3.2.7 on 2021-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='defence_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='healing_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
