# Generated by Django 3.2.7 on 2021-09-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='drain_attack_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='fire_attack_cost',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='golem_attack_cost',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='ice_attack_cost',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='thunder_attack_cost',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
