# Generated by Django 3.2.7 on 2021-09-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210928_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.hand'),
        ),
    ]
