# Generated by Django 3.2.7 on 2021-09-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210927_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='in_fullversion',
            new_name='in_freeversion',
        ),
    ]
