# Generated by Django 3.2.7 on 2021-09-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210927_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='thunder_attack_cost',
            new_name='lightning_attack_cost',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='thunder_attack_power',
            new_name='lightning_attack_power',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='thunder_defense',
            new_name='lightning_defense',
        ),
    ]
