# Generated by Django 3.2.7 on 2021-09-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_player_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.card'),
        ),
    ]
