# Generated by Django 3.2.7 on 2021-09-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_hand_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hand',
            new_name='Hand_card',
        ),
    ]
