# Generated by Django 3.2.7 on 2021-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_player_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(to='profiles.Hand_card'),
        ),
    ]
