# Generated by Django 3.2.7 on 2021-10-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_healing_attack_cost_player_healing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='healing_cost',
            field=models.IntegerField(default=2),
        ),
    ]
