# Generated by Django 3.2.7 on 2021-10-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
