# Generated by Django 3.2.7 on 2021-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fire_attack_cost',
            field=models.IntegerField(default=3),
        ),
    ]
