# Generated by Django 3.2.7 on 2021-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_player_fire_attack_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='health_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
