# Generated by Django 3.2.7 on 2021-10-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20211022_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='skill_style',
            field=models.CharField(choices=[('LN', 'Lightning'), ('FR', 'Fire'), ('GL', 'Golem'), ('DR', 'Drain'), ('IC', 'Ice'), ('HL', 'Heal'), ('MN', 'Mana')], max_length=2),
        ),
    ]
