# Generated by Django 3.2.7 on 2021-10-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_card_skill_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hand_card',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='player_type',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk']},
        ),
    ]
