# Generated by Django 3.2.7 on 2021-10-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20211026_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_type',
            new_name='PlayerType',
        ),
    ]
