# Generated by Django 3.2.7 on 2021-10-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_rename_player_type_playertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hand_card',
            new_name='HandCard',
        ),
    ]
