# Generated by Django 3.2.7 on 2021-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_rename_hand_card_handcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='image_attack_url',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='image_die_url',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='image_idle_url',
        ),
    ]
