# Generated by Django 3.2.7 on 2021-09-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_game_floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('current_phase', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_fullversion', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=254)),
                ('image_idle', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_idle_url', models.URLField(blank=True, null=True)),
                ('image_attack', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_attack_url', models.URLField(blank=True, null=True)),
                ('image_die', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_die_url', models.URLField(blank=True, null=True)),
                ('max_health', models.IntegerField(default=0)),
                ('attack_power', models.IntegerField(default=0)),
                ('skill_style', models.CharField(choices=[('LN', 'Lightning'), ('FR', 'Fire'), ('GL', 'Golem'), ('DR', 'Drain'), ('IC', 'Ice')], max_length=2)),
                ('attack_phase', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=1)),
                ('xp_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game_floor_enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_current', models.IntegerField(blank=True, null=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.enemy')),
                ('game_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.current_game_floor')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.BigIntegerField(default=0)),
                ('game_step', models.CharField(choices=[('1', 'Step 1'), ('2', 'Step 2'), ('3', 'Step 3'), ('4', 'Step 4'), ('5', 'Step 5')], max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.player')),
            ],
        ),
        migrations.AddField(
            model_name='current_game_floor',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.game'),
        ),
    ]
