# Generated by Django 3.2.7 on 2021-09-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_game_floor',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='game_floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='battle.current_game_floor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_step',
            field=models.CharField(choices=[('1', 'Step 1'), ('2', 'Step 2'), ('3', 'Step 3'), ('4', 'Step 4'), ('5', 'Step 5')], default=1, max_length=1),
        ),
    ]
