# Generated by Django 3.2.7 on 2021-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='attack_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_attack',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_attack_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_die',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_die_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_idle',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enemy',
            name='image_idle_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='xp_value',
            field=models.IntegerField(default=0),
        ),
    ]
