# Generated by Django 3.2.7 on 2021-09-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='in_fullversion',
            new_name='in_freeversion',
        ),
    ]
