# Generated by Django 3.2.7 on 2021-09-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20210922_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('card_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.card')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.hand_cards'),
        ),
        migrations.DeleteModel(
            name='Hand_card',
        ),
    ]
