# Generated by Django 3.2.7 on 2021-09-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20210928_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_floor',
            new_name='current_game_floor',
        ),
        migrations.RemoveField(
            model_name='game_floor_enemy',
            name='game_floor',
        ),
        migrations.AddField(
            model_name='current_game_floor',
            name='Enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.game_floor_enemy'),
        ),
        migrations.AlterField(
            model_name='game_floor_enemy',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.enemy'),
        ),
    ]
