# Generated by Django 3.2.7 on 2021-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20210922_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='current_game_floor',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='health_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hand_card',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_attack',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_attack_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_die',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_die_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_idle',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='player_type',
            name='image_idle_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
