# Generated by Django 3.2.7 on 2021-09-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_auto_20210922_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand_cards',
            old_name='card_1',
            new_name='card',
        ),
    ]
