# Generated by Django 3.2.7 on 2021-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_auto_20210928_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_floor_enemy',
            name='health_current',
        ),
        migrations.AddField(
            model_name='enemy',
            name='health_current',
            field=models.IntegerField(null=True),
        ),
    ]
