# Generated by Django 3.2.7 on 2021-09-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_rename_card_1_hand_cards_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hand_cards',
            new_name='Hand_card',
        ),
    ]
