# Generated by Django 3.2.7 on 2021-09-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20210928_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='xp_value',
        ),
    ]
