# Generated by Django 3.2.7 on 2021-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_rename_hand_cards_hand_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(to='battle.Hand_card'),
        ),
    ]
