# Generated by Django 3.2.7 on 2021-10-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_auto_20211005_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='attack_phase',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='attack_power',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='health_current',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='max_health',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='skill_style',
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='attack_phase',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='attack_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='health_current',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='max_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_floor_enemy',
            name='skill_style',
            field=models.CharField(choices=[('LN', 'Lightning'), ('FR', 'Fire'), ('GL', 'Golem'), ('DR', 'Drain'), ('IC', 'Ice'), ('HL', 'Heal')], default='LN', max_length=2),
        ),
        migrations.RemoveField(
            model_name='current_game_floor',
            name='Enemy',
        ),
        migrations.AddField(
            model_name='current_game_floor',
            name='Enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.game_floor_enemy'),
        ),
    ]
