# Generated by Django 3.2.7 on 2021-10-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_auto_20211005_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_game_floor',
            old_name='Enemy',
            new_name='enemy',
        ),
    ]
