# Generated by Django 3.2.7 on 2021-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0012_game_completed_game_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='completed_game_floors',
            field=models.IntegerField(default=1),
        ),
    ]
