# Generated by Django 3.2.7 on 2021-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_alter_game_completed_game_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_game_floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='battle.current_game_floor'),
        ),
    ]
