# Generated by Django 3.2.7 on 2021-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0021_auto_20211016_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_floor_enemy',
            name='has_attacked',
            field=models.BooleanField(default=False),
        ),
    ]
