# Generated by Django 3.2.7 on 2021-10-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0022_game_floor_enemy_has_attacked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_floor_enemy',
            old_name='max_health',
            new_name='health_max',
        ),
    ]
