# Generated by Django 3.2.7 on 2021-10-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0026_alter_game_floor_enemy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_game_floor',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['pk']},
        ),
    ]
