# Generated by Django 3.2.7 on 2021-10-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0027_auto_20211026_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_floor_enemy',
            new_name='GameFloorEnemy',
        ),
    ]
