# Generated by Django 3.2.7 on 2021-10-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0028_rename_game_floor_enemy_gamefloorenemy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_game_floor',
            new_name='CurrentGameFloor',
        ),
    ]
