# Generated by Django 3.2.7 on 2021-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0029_rename_current_game_floor_currentgamefloor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='image_attack_url',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='image_die_url',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='image_idle_url',
        ),
    ]
